### ISSUE TITLE
lookup 'sops' not found

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible-collections/community.sops#16]
# Problem

I don't know why, but only writing

```
ansible localhost -m debug -a msg="{{ lookup('sops', 'test.yml') }}"
```

leads to...

```
localhost | FAILED! => {
    "msg": "lookup plugin (sops) not found"
}
```

The current solution is to reference the fully qualified lookup name:

```
ansible localhost -m debug -a msg="{{ lookup('community.sops.sops', 'test.yml') }}"
```

# Context
* ansible 2.10.1rc3
* python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

Installed 'community.sops' with

```
ansible-galaxy collection install -r requirements.yml
```

... whereas requirements.yml contains:

```
collections:
  - name: https://github.com/ansible-collections/community.sops.git
    type: git
```

**Comment by felixfontein** [comment]
The lookup's FQCN is `community.sops.sops`, not `sops`. So you need to write `community.sops.sops` (as you already found out).

**Comment by ThomasSteinbach** [comment]
Thank you for clarification.

Just to get it right: Might it be that the documentation is wrong here?
https://github.com/ansible-collections/community.sops/blob/c53d1f0f2818f7037c8e7d749c86339dfe421e26/plugins/lookup/sops.py#L53

**Comment by felixfontein** [comment]
Yes, it's definitely wrong. Thanks for noticing! Feel free to create a PR to fix it, otherwise I might be able to do that over the lunch break.

**Comment by felixfontein** [comment]
@endorama thanks for fixing it!
