### ISSUE TITLE
sops vars plugin generates malformed sops commands

### ISSUE THREAD

**Issue by niuleh** [ansible-collections/community.sops#195]
##### SUMMARY

vars plugin produces an `ErrorGeneric` SopsError with error message `msg="flag provided but not defined: -config"`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.sops.sops vars plugin

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.8]
  config file = /workspaces/monodevcontainer/ansible/internal/ansible.cfg
  configured module search path = ['/home/code/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/code/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.2 (main, Feb 21 2024, 00:00:00) [GCC 14.0.1 20240217 (Red Hat 14.0.1-0)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/code/.ansible/collections/ansible_collections
Collection     Version
-------------- -------
community.sops 1.8.0  
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /workspaces/monodevcontainer/ansible/internal/ansible.cfg
DEFAULT_HASH_BEHAVIOUR(/workspaces/monodevcontainer/ansible/internal/ansible.cfg) = merge
DEFAULT_HOST_LIST(/workspaces/monodevcontainer/ansible/internal/ansible.cfg) = ['/workspaces/monodevcontainer/ansible/internal/inventories/dev']
DEFAULT_REMOTE_USER(/workspaces/monodevcontainer/ansible/internal/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/workspaces/monodevcontainer/ansible/internal/ansible.cfg) = ['/workspaces/monodevcontainer/ansible/internal/roles']
EDITOR(env: EDITOR) = code --wait
VARIABLE_PLUGINS_ENABLED(/workspaces/monodevcontainer/ansible/internal/ansible.cfg) = ['host_group_vars', 'community.sops.sops']
```

##### OS / ENVIRONMENT

Host OS Fedora 40
Ansible executed in podman container based on Fedora 40

##### STEPS TO REPRODUCE

See example inventory and example playbook below. Use `echo "debug_secret_var: my_awesome_secret" | sops encrypt /dev/stdin >> ~/inventory/host_vars/dev-generic.vbox.arpa/secrets.sops.yml` to create encrypted file.

Inventory:
```
~/inventory
├── hosts.yaml
└── host_vars
    └── dev-generic.vbox.arpa
        ├── secrets.sops.yml  
        └── vars.yml
```
Playbook:
```yaml
- name: Debug sops vars plugin
  hosts: dev-generic.vbox.arpa
  tasks:
  - debug: 
      msg: "secret: '{{ debug_secret_var }}'"
```

##### EXPECTED RESULTS

```
> ansible-playbook playbooks/debug_sops_vars.yml
(...)
TASK [debug] ***************************************************************************************************************************************************************
ok: [dev-generic.vbox.arpa] => {
    "msg": "secret: 'my_awesome_secret'"
}
(...)
```
##### ACTUAL RESULTS

```paste below
ERROR! error with file /workspaces/monodevcontainer/ansible/internal/inventories/dev/host_vars/dev-generic.vbox.arpa.sops.yml: ErrorGeneric exited with code 1: [CMD]    time="2024-07-17T13:37:34Z" level=fatal msg="flag provided but not defined: -config"
```

**Comment by felixfontein** [comment]
Are you configuring the config path somewhere? Like with the `ANSIBLE_SOPS_CONFIG_PATH` env variable, or with `config_path` in `[community.sops]` in ansible.cfg?

**Comment by niuleh** [comment]
> Are you configuring the config path somewhere? Like with the `ANSIBLE_SOPS_CONFIG_PATH` env variable, or with `config_path` in `[community.sops]` in ansible.cfg?

Yes, see contents of the "ansible.cfg" file:
``` ini
(...)
vars_plugins_enabled = host_group_vars,community.sops.sops

[community.sops]
config_path = .sops.yaml
vars_stage = all
(...)
```

**Comment by felixfontein** [comment]
Since `.sops.yaml` is the default config file name, try commenting `config_path = .sops.yaml` out, that should work around this bug for now.

**Comment by niuleh** [comment]
> Since `.sops.yaml` is the default config file name, try commenting `config_path = .sops.yaml` out, that should work around this bug for now.

Okay, that seems to work. 

If I wanted to fix this, would I have to separate global options from command specific options and pass them to AnsibleRunner._run_command() in the correct order? Ideally we'd want `command = ["sops", "--config", "path/to/config", "decrypt", "--input-type", "yaml", "--output-type", "yaml", "path/to/secrets.sops.yaml"]`, right?

**Comment by felixfontein** [comment]
Yes. (I tried to implement that in #197.)
