### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by endorama** [ansible-collections/community.sops#21]
Opening this task to coordinate the release of the first version :tada: 

Follows #5 and #8 

@felixfontein is there something else I need to do before this release? Will the Changelog be created automatically or should I take care of that?

---

Release process:
- push tag `0.1.0`

**Comment by felixfontein** [comment]
You need to take care of the changelog (and bumping galaxy.yml version etc.). The exact process is described here: https://github.com/ansible/community/wiki/ReleasingCollections#releasing-without-release-branches-for-smaller-collections

What I did in other projects is create a PR with most of the steps (except 7 and 8). Then it is possible for others to check whether it looks good; if it does, the PR can be merged, the last commit tagged and the tag pushed, and another commit added for bumping the version.

**Comment by endorama** [comment]
@felixfontein while building the `CHANGELOG` I notice the `load_vars` plugin is not included in the as "new plugin". I noticed there is no documentation in the `plugins/action/load_vars.py` but only in the `plugins/modules/load_vars.py` file. Is this expected?

**Comment by felixfontein** [comment]
@endorama action plugins are documented by adding module "stubs" which contain the documentation (and no "real" code). The `load_vars` plugin should show up under "New Modules", since action plugins are indistinguishable from modules to the user.

**Comment by endorama** [comment]
I think it's time for our first release! Plugins have been merged and the documentation is ok.

@felixfontein if you agree I'd start the release process again

**Comment by felixfontein** [comment]
@endorama sounds great! :) I'm looking forward to the first official release!

**Comment by felixfontein** [comment]
@endorama any update on this?

**Comment by endorama** [comment]
Tagged and pushed > https://github.com/ansible-collections/community.sops/releases/tag/0.1.0

**Comment by endorama** [comment]
@felixfontein should you be listed in `Authors` field? I'm not sure what that implies, but I think is deserved :)

Now that the tag is pushed, where I can observe the build (and if anything is going smooth)?

**Comment by felixfontein** [comment]
Zuul is handling the publishing: https://dashboard.zuul.ansible.com/t/ansible/stream/3e2087c39c05400da8e845e992ad5887?logfile=console.log

(The generic dashboard URL is https://dashboard.zuul.ansible.com/t/ansible/status)

**Comment by felixfontein** [comment]
Since this is a small collection, it's already done: https://galaxy.ansible.com/community/sops \o/

**Comment by felixfontein** [comment]
@felixfontein about the Authors field: whatever you want :) I'm already mentioned in the author field of the modules/action plugins I contributed and show up in the git history, that's also fine for me ;)

**Comment by felixfontein** [comment]
I added a small announcement for the next Bullhorn newsletter (ansible/community#546): https://github.com/ansible/community/issues/546#issuecomment-715329818

**Comment by felixfontein** [comment]
BTW, changelog fragments use reStructuredText and not MarkDown, so use double backticks next time :)

**Comment by endorama** [comment]
@felixfontein :facepalm: I will! next time I'm going to open a PR as you suggested (I'm even trying to automate that with GitHub Actions so it's automated and I avoid errors :sweat:)

Closing this issue :tada:

**Comment by felixfontein** [comment]
@endorama hehe yeah that happens :)
