### ISSUE TITLE
load_vars with static=false

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.sops#25]
Looks like I forgot to create the issue for #19.

Anyway, I now found out that soon there will be a change in Ansible (which is backported also to stable-2.10 and stable-2.9) which will break `static: false`.

Maybe we should remove that functionality before actually releasing, because it is guaranteed to stop working soon. @endorama what do you think?

**Comment by felixfontein** [comment]
My plan right now is to remove the `static` option, and add a `template_values` option instead (type `bool`, default `false`), which when set to `true` will template all string values found in the file. This is not a 100% replacement, but will at least work in my own personal use-cases, and it can be implemented safely (i.e. it doesn't use hacks that might stop working anytime).

**Comment by endorama** [comment]
@felixfontein agreed. Will this become useless once the related Ansible issue (https://github.com/ansible/ansible/issues/71831) is solved? Just to keep this in mind, as I don't expect it to be reviewed and fixed anytime soon.
