### ISSUE TITLE
Inclusion in Ansible 3.0.0

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.sops#31]
##### SUMMARY
While it not totally clear yet what the conditions will be for new collections to be included in Ansible 2.11, I think community.sops has good chances:
- we satisfy almost most things from https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst (currently missing: a 1.0.0 release);
- we have active maintainers;
- the quality of this collection is good, we have working integration tests and pass all sanity tests.

If we want to get included, I suggest we use this ticket to track that.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
collection

**Comment by endorama** [comment]
That would be very cool in my opinion!

I'm going to do the `0.1.0` release right now, so we can work towards our first stable release.

Planned ETA to fullfill all requirements to get included in Ansible 2.11?

**Comment by felixfontein** [comment]
An ETA is as much not known as the exact conditions ;) But it will probably be ~end of this year. Ansible 2.11 is planned for January or February 2021.

**Comment by felixfontein** [comment]
The conditions have now been defined:
 - The general requirements are listed here: https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst
 - The process is explained here: https://github.com/ansible/community/issues/546#issuecomment-743358625

**Comment by endorama** [comment]
I setup a milestone to track this https://github.com/ansible-collections/community.sops/milestone/1

**Comment by felixfontein** [comment]
@endorama would be great if you could take another look. We should really get 1.0.0 on the way soon.

**Comment by endorama** [comment]
Milestone completed, I'll release `1.0.0` soon and then open the relevant discussion for inclusion.

**Comment by felixfontein** [comment]
@endorama do you want https://github.com/ansible-collections/community.sops/pull/47 included in 1.0.0? (I can also update all `version_added`s there to 1.0.0 and bump galaxy.yml to 1.0.0.)

**Comment by endorama** [comment]
Yes! I went ahead and did it. Going to merge it now.

**Comment by felixfontein** [comment]
Adjusted the issue title to reality ;)

**Comment by endorama** [comment]
Tag submitted, waiting for Zuul to pick up the build!

**Comment by felixfontein** [comment]
> This release is expected to be included in Ansible 3.0.0.

You make bold claims :D

**Comment by endorama** [comment]
Yes, I pushed the wrong tag :( But I also immediately deleted it, it seems like the system already reacted (is not very clear to me how Zuul is linked to this repo).

Do you know how to fix it?

**Comment by felixfontein** [comment]
I think Zuul is directly informed by GitHub about any new commit / tag (probably some webhooks). I think the best way is to fix the changelog to mention the 1.0.1 release, and create a new 1.0.2 release which has a correct changelog (including an entry for itself). I've already prepared a PR for that, #48.

**Comment by endorama** [comment]
Version `1.0.2` released, posted for review (https://github.com/ansible-collections/ansible-inclusion/discussions/9) and posted in Bullhorn issue (https://github.com/ansible/community/issues/546#issuecomment-761087165) :tada:

**Comment by felixfontein** [comment]
Closing since this is done.
