### ISSUE TITLE
0.2.0 release

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.sops#38]
I'm planning to release 0.2.0 of this collection in a few days if nobody (in particular @endorama) complains :)

**Comment by felixfontein** [comment]
I'm working on a release now.

**Comment by felixfontein** [comment]
The release is done!

**Comment by endorama** [comment]
@felixfontein I'm deeply sorry I had to do this yourself. But thanks a lot, very appreciated.

**Comment by felixfontein** [comment]
@endorama no problem, I did so many collection releases already this year already, one more doesn't hurt at all ;)
