### ISSUE TITLE
Collection requirements: collection  infrastructure

### ISSUE THREAD

**Issue by endorama** [ansible-collections/community.sops#39]
Follows https://github.com/ansible-collections/overview/blob/5185727690d3fdef2d7ef44ae893e2c2ac9b5f6e/collection_requirements.rst#collection-infrastructure

## Collection Infrastructure

- [x] MUST have a publicly available issue tracker, that does not require a paid level of service to create an account or view issues.
- [x] Collections MUST have a Code of Conduct (CoC)
	- The collection's CoC MUST be compatible with the Ansible CoC
	- Collections SHOULD consider using the Ansible CoC if they do not have a CoC that they consider better
	- The Diversity and Inclusion working group may evaluate all CoCs and object to a collection's inclusion based on the CoCs contents
- [x] MUST be published to Ansible Galaxy.

**Comment by endorama** [comment]
@felixfontein how should I include the CoC? Is a link to https://docs.ansible.com/ansible/latest/community/code_of_conduct.html ok or should be included like a LICENSE file?

**Comment by endorama** [comment]
This collection is already [published to Ansible Galaxy](https://galaxy.ansible.com/community/sops)

**Comment by felixfontein** [comment]
@endorama we already reference the Ansible CoC: https://github.com/ansible-collections/community.sops#more-information Having a link should be fine.

**Comment by endorama** [comment]
Closing this one then!
