### ISSUE TITLE
Renaming master branch to main

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.sops#4]
The Ansible team decided to rename the `master` branch in all Ansible-controlled collections to `main` (see ansible-collections/overview#83 and ansible-collections/overview#87 for history and more information). This also applies to `community.sops`. My suggestion would be to do this soon, especially before a first release is done, and before more people start cloning/forking this repository.

Right now, there are two forks (one by @liptanbiswas and mine), and probably some clones (@endorama surely has one). Information on updating local clones can be found here: https://github.com/ansible/community/wiki/Changing-the-git-default-branch-to-main#updating-local-clones Information on updating forks on github: https://github.com/ansible/community/wiki/Changing-the-git-default-branch-to-main#updating-a-fork-on-github

@endorama please tell us when we should do this change.

**Comment by felixfontein** [comment]
CC @gundalow

**Comment by felixfontein** [comment]
If nobody complains, I'll do this change on Wednesday morning (European time).

**Comment by endorama** [comment]
No complains from me :smile: 

@felixfontein I wanted to do it myself but it seems my privileges are limited. I already pushed a `main` branch based on `master` so feel free to change default branch as you see fit.

**Comment by felixfontein** [comment]
Ha, I know I forgot something this mornig :D Anyway, I think you already did most of the work - I've changed the codecov configuration to use `main` as the default branch. I don't have access to the GitHub branch settings either, but I've pinged @gundalow on IRC for that (and to delete `master `afterwards). Might have to wait until tomorrow though :)

**Comment by gundalow** [comment]
Default branch changed.
Should I delete `master` now?

**Comment by felixfontein** [comment]
@gundalow yes, it can be deleted. It will only cause confusion and there are no links to it.

**Comment by gundalow** [comment]
Deleted, thanks!

**Comment by felixfontein** [comment]
Awesome! Then this change is done for this repo!

@liptanbiswas @mhumeSF please adjust your forks.

I'm closing this issue; in case you need help, feel free to still ask here.
