### ISSUE TITLE
Collection requirements: repository structure

### ISSUE THREAD

**Issue by endorama** [ansible-collections/community.sops#40]
Following https://github.com/ansible-collections/overview/blob/5185727690d3fdef2d7ef44ae893e2c2ac9b5f6e/collection_requirements.rst#repo-structure

galaxy.yml
----------

* [x] The ``tags`` field MUST be set
* [x] Collection dependencies used are expected to be stable, hence MUST be set to ``'>=1.0.0'``

  * This means that all collection dependencies have to specify lower bounds on the versions, and these lower bounds should be stable releases, and not versions of the form 0.x.y.
  * When creating new collections where collection dependencies are also under development, you need to watch out since Galaxy checks whether dependencies exist in the required versions:

    1. Assume that ``foo.bar`` depends on ``foo.baz``
    2. First release ``foo.baz`` as 1.0.0.
    3. Then modify ``foo.bar``'s ``galaxy.yml`` to specify ``'>=1.0.0'`` for ``foo.baz``
    4. Finally release ``foo.bar`` as 1.0.0

README.md
---------

- [x] MUST have a ``README.md`` in the root of the Collection, see [`collection_template/README.md`](https://github.com/ansible-collections/collection_template/blob/main/README.md) for an example.

meta/runtime.yml
----------------
Example: [`meta/runtime.yml`](https://github.com/ansible-collections/collection_template/blob/main/meta/runtime.yml)

* [x] MUST define the minimum version of Ansible which this collection works with

  * If the collection works with Ansible 2.9, then this should be set to `>=2.9.10`
  * It's usually better to avoid adding `<2.11` as a restriction, since this for example makes it impossible to use the collection with the current ansible-base devel branch (which has version 2.11.0.dev0)

Modules & Plugins
------------------

### Documentation

All module and plugin `DOCUMENTATION` and `RETURN` MUST:

* [x] Use the FQCN for `M(...)` and `- module:` references of `seealso` subsections. See `Linking within module documentation <https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#linking-within-module-documentation>`_
* [x] Use the field `version_added` to document the version of the collection for which an option, module or plugin was added.

  * Use collection version numbers for `version_added`, and not Ansible version numbers or other unrelated version numbers.
  * If you for some reason really have to specify version numbers of Ansible or of another collection, you have to provide `version_added_collection`. We strongly recommend to NOT do this.
  * Not every option, module or plugin must have `version_added`. You should use it to mark when new content (modules, plugins, options) were added to the collection. The values are shown in the documentation, and this can be very useful for your users.

All module and plugin `EXAMPLES` MUST:

* [x] Use FQCN for module (or plugin) name.
* [x] For modules (or plugins) left in ansible-base use `ansible.builtin.` as a FQCN prefix, for example, `ansible.builtin.template`

Other items:

* [x] You MUST Use the FQCN for `extends_documentation_fragment:`, unless you are referring to doc_fragments from ansible-base
* [x] The `CONTRIBUTING.md` (or `README.md`) file MUST state what types of contributions (pull requests, feature requests, and so on) are accepted and any relevant contributor guidance. Issues (bugs and feature request) reports must always be accepted

**Comment by endorama** [comment]
@felixfontein last one missing is "For modules (or plugins) left in ansible-base use ansible.builtin. as a FQCN prefix, for example, ansible.builtin.template"
I fail to understand what "left in ansible-base" mean, but if I got it right this should be ok as there are none?

**Comment by felixfontein** [comment]
@endorama that were most of the changes in https://github.com/ansible-collections/community.sops/pull/44/files :)

**Comment by endorama** [comment]
Deal! So I'd say we can close this, awesome!

**Comment by felixfontein** [comment]
And the modules left in ansible-base are here: https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/

**Comment by felixfontein** [comment]
@endorama thanks for reviewing and merging all the PRs!
