### ISSUE TITLE
Collection requirements: licensing

### ISSUE THREAD

**Issue by endorama** [ansible-collections/community.sops#41]
Follows https://github.com/ansible-collections/overview/blob/5185727690d3fdef2d7ef44ae893e2c2ac9b5f6e/collection_requirements.rst#licensing

## Licensing

- [x] At the moment, `module_utils` must be licensed under the BSD-2-clause or GPL-3.0-or-later license and all other content must be licensed under the GPL-3.0-or-later. 

> We will have a list of other open source licenses which are allowed as soon as we get Red Hat's legal team to approve such a list for us.

**Comment by felixfontein** [comment]
We have two module_utils:
1. io.py - GPLv3
2. sops.py - BSD 2-clause

So everything's in order.
