### ISSUE TITLE
Lookup plugin strips newline by default creating issues with ssh private keys

### ISSUE THREAD

**Issue by pcuttriss** [ansible-collections/community.sops#61]
##### SUMMARY

Lookup plugin strips newline by default creating issues with ssh private keys. When copying the key the following error may be observed when trying to use the resulting key in an ssh session due to the default nature of the lookup plugin stripping trailing newlines. 

Load key "/home/my_user_id/.ssh/my_ssh_private_key": invalid format

######################
Current documentation:
######################
### **lookup plugin**

The lookup plugin can be accessed with the community.sops.sops key.

Examples:

tasks:
  - name: Output secrets to screen (BAD IDEA!)
    ansible.builtin.debug:
        msg: "Content: {{ lookup('community.sops.sops', '/path/to/sops-encrypted-file.enc.yaml') }}"

  - name: Add SSH private key
    ansible.builtin.copy:
        content: "{{ lookup('community.sops.sops', user + '-id_rsa') }}"
        dest: /home/{{ user }}/.ssh/id_rsa
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600
    no_log: true  # avoid content to be written to log

#######################################################
Proposed update: add the option for rstrip to the ssh key example
#######################################################
**### lookup plugin**

The lookup plugin can be accessed with the community.sops.sops key.

Examples:

tasks:
  - name: Output secrets to screen (BAD IDEA!)
    ansible.builtin.debug:
        msg: "Content: {{ lookup('community.sops.sops', '/path/to/sops-encrypted-file.enc.yaml') }}"

  - name: Add SSH private key
    ansible.builtin.copy:
        content: "{{ lookup('community.sops.sops', user + '-id_rsa'**,  rstrip='no'**) }}"
        dest: /home/{{ user }}/.ssh/id_rsa
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600
    no_log: true  # avoid content to be written to log

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

Lookup plugin

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
```

**Comment by endorama** [comment]
Hi @pcuttriss may you confirm this is only a documentation issue? The proposal look fine to me if this is the case.

**Comment by felixfontein** [comment]
Since `rstrip` exists and can be set to `false`, I would say this is 'only' a documentation issue.

**Comment by pcuttriss** [comment]
This is purely a documentation issue.

I hit this yesterday and spent a while working out what the problem was on the linux side…..and thought it’s a nice easy doc addition to avoid folk having the same problem.

And I would also like to extend my thanks to the team for making sops available in ansible in such a useable form.

Paul

**Comment by felixfontein** [comment]
Interestingly, my ssh (OpenSSH_8.6p1, OpenSSL 1.1.1k  25 Mar 2021) doesn't seem to care about a newline at the end.

**Comment by felixfontein** [comment]
I created a PR (#62) to update the docs. I've chosen `rstrip=false` over `rstrip='no'` :)

**Comment by endorama** [comment]
Agreed, @felixfontein I reviewed and merged the PR.

@pcuttriss thank you for the contribution!
