### ISSUE TITLE
Vars plugin isn't loading variables

### ISSUE THREAD

**Issue by larsks** [ansible-collections/community.sops#63]
##### SUMMARY

I'm testing out the `community.sops` collection and the vars plugin does not appear to be behaving as expected.

My directory structure looks like this:

```
.
├── ansible.cfg
├── group_vars
│   └── all.sops.yaml
├── playbook.yml
├── requirements.yml
└── .sops.yaml
```

Where `ansible.cfg` looks like:

```
[defaults]
vars_plugins_enabled = host_group_vars,community.sops.sops
```

And `playbook.yml` looks like:

```
- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        var: users
```

And `.sops.yaml` looks like:

```
---
creation_rules:
  - pgp: >-
      3E70A502BB5255B6BB8E86BE362D63A80853D4CF
```

And `requirements.yml` looks like:

```
collections:
  - name: git+https://github.com/ansible-collections/community.sops
    version: main
```

(Running `ansible-galaxy collection install ...` just now should have installed commit 151f986.)

I have created `group_vars/all.sops.yaml` by running:

```
sops group_vars/all.sops.yaml
````

I can successfully decrypt this file with `sops`:

```
$ sops -d group_vars/all.sops.yaml
users:
-   name: alice
    password: secret
```

But running the playbook fails with:

```
TASK [debug] *********************************************************************************************************************************************************************************
ok: [localhost] => {
    "users": "VARIABLE IS NOT DEFINED!"
}
```

It look as if the the sops vars plugin is making no attempt to decrypt `group_vars/all.sops.yaml`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.sops vars plugin

##### ANSIBLE VERSION

```paste below
ansible 2.10.8
  config file = /home/lars/tmp/sopstest/ansible.cfg
  configured module search path = ['/home/lars/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lars/.local/lib/python3.9/site-packages/ansible
  executable location = /home/lars/.local/bin/ansible
  python version = 3.9.4 (default, Apr  6 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```

##### CONFIGURATION

```paste below
VARIABLE_PLUGINS_ENABLED(/home/lars/tmp/sopstest/ansible.cfg) = ['host_group_vars', 'community.sops.sops']
```

##### OS / ENVIRONMENT

Fedora 33

##### STEPS TO REPRODUCE
(see above)

##### EXPECTED RESULTS

I expected the playbook to output the contents of the `users` variable defined in `group_vars/all.sops.yaml`.

##### ACTUAL RESULTS
The playbook was not aware of a `users` variable.

**Comment by felixfontein** [comment]
I can't reproduce this. Also please note that there is/was a bug/issue in ansible-base that implicit localhost is not part of the `all` group, which might be causing this. Maybe try to add an inventory where `localhost` is explicitly listed.

**Comment by larsks** [comment]
Everything works fine for me running in a container built to try to reproduce the problem, so apparently there is something amiss in my environment. Sorry for the noise!

**Comment by felixfontein** [comment]
Maybe ansible didn't find the collection for some reason? Sometimes you need to add multiple `-v` to get useful information.
