### ISSUE TITLE
SOPS return code check is incorrect

### ISSUE THREAD

**Issue by Lycowolf** [ansible-collections/community.sops#82]
##### SUMMARY
https://github.com/ansible-collections/community.sops/blob/main/plugins/module_utils/sops.py#L177 (and similarly in the encrypt() method later) checks if SOPS failed by doing
```python
if exit_code > 0: 
  # handle error
```
This is incorrect: on POSIX systems, the return code can be negative if the child was killed by a signal (even if it killed itself, e. g. by SIGABRT, SIGSEGV etc.) as documented in [the manual](https://docs.python.org/3/library/subprocess.html#subprocess.CompletedProcess.returncode). When this happen, Ansible continues without an error, but uses undecryped data (don't know why, probably builtin vars plugin takes over?). This results in very hard-to-debug problems.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
sops collection, module_utils/sops.py

##### ANSIBLE VERSION

doesn't matter

##### COLLECTION VERSION

all of them

##### CONFIGURATION

doesn't matter

##### OS / ENVIRONMENT

all Linux (probably all UNIXes)

##### STEPS TO REPRODUCE

I found this when Git (un)helpfully converted newlines in the binary to CRLF. The resulting binary, when run, got killed by SIGTRAP immediately after execve().

You could probably replace sops binary with a shell script that kills itself or something.

##### EXPECTED RESULTS

Ansible fails with an error, describing what happened (e. g. "SOPS killed by signal no. 5)"

##### ACTUAL RESULTS

Ansible continues without an error, using ciphertext as data

**Comment by felixfontein** [comment]
I created #83 to address this.

**Comment by Lycowolf** [comment]
Looks good to me

**Comment by endorama** [comment]
@Lycowolf thank you for the issue!
@felixfontein thanks for the fix!
